const uuidv4 = require('uuid/v4');

const Base = require('../Base');

class Data extends Base {
  // This class is auto generated by Cloud Events Generator
  // (https://github.com/michaelawyu/cloud-events-generator).
  //
  // Do not edit the class manually.

  constructor ({ bypassCheck = false, orderId = null, email = null, paymentErrType = null, paymentErrMessage = null } = {}) {
    // Data - a model defined in Cloud Events Generator
    //
    // Param orderId: The orderId of this Data.
    // Type of orderId: String
    // Param email: The email of this Data.
    // Type of email: String
    // Param paymentErrType: The paymentErrType of this Data.
    // Type of paymentErrType: String
    // Param paymentErrMessage: The paymentErrMessage of this Data.
    // Type of paymentErrMessage: String

    super();
    this.paramTypes = {
      orderId: String,
      email: String,
      paymentErrType: String,
      paymentErrMessage: String
    };
    this.attributeMap = {
      orderId: 'orderId',
      email: 'email',
      paymentErrType: 'paymentErrType',
      paymentErrMessage: 'paymentErrMessage'
    };

    if (!bypassCheck) {
      this.orderId = orderId;
      this.email = email;
      this.paymentErrType = paymentErrType;
      this.paymentErrMessage = paymentErrMessage;
    } else {
      this._orderId = orderId;
      this._email = email;
      this._paymentErrType = paymentErrType;
      this._paymentErrMessage = paymentErrMessage;
    }
  }

  static fromObject (obj) {
    const model = new this({ bypassCheck: true });
    Object.keys(model.paramTypes).forEach(function (key) {
      const baseName = model.attributeMap[key];
      const typ = model.paramTypes[key];
      if (Object.prototype.hasOwnProperty.call(obj, baseName) && obj[baseName]) {
        if (Array.isArray(typ)) {
          const itemTyp = typ[0];
          const arr = [];
          obj[baseName].forEach(function (elem) {
            if (itemTyp.fromObject === undefined) {
              arr.push(itemTyp(elem));
            } else {
              arr.push(itemTyp.fromObject(elem));
            }
          });
          model[key] = arr;
        } else {
          if (typ.fromObject === undefined) {
            model[key] = typ(obj[baseName]);
          } else {
            model[key] = typ.fromObject(obj[baseName]);
          }
        }
      } else {
        model[key] = null;
      }
    });
    return model;
  }

  get orderId () {
    // Gets the orderId of this Data.
    //
    // order id
    //
    // returns: orderId
    // returnType: String

    return this._orderId;
  }

  set orderId (orderId) {
    // Sets the orderId of this Data.
    //
    // order id
    //
    // returns: undefined
    // returnType: undefined

    if (orderId === undefined) {
      this._orderId = null;
    } else {
      this._orderId = orderId;
    }
  }

  get email () {
    // Gets the email of this Data.
    //
    // email address
    //
    // returns: email
    // returnType: String

    return this._email;
  }

  set email (email) {
    // Sets the email of this Data.
    //
    // email address
    //
    // returns: undefined
    // returnType: undefined

    if (email === undefined) {
      this._email = null;
    } else {
      this._email = email;
    }
  }

  get paymentErrType () {
    // Gets the paymentErrType of this Data.
    //
    // error type of failed payment
    //
    // returns: paymentErrType
    // returnType: String

    return this._paymentErrType;
  }

  set paymentErrType (paymentErrType) {
    // Sets the paymentErrType of this Data.
    //
    // error type of failed payment
    //
    // returns: undefined
    // returnType: undefined

    const allowedValues = ["INTERNAL", "CARD_ERROR", "NONE"]
    if (!allowedValues.includes(paymentErrType)) {
      throw Error(`Invalid value for paymentErrType (${ paymentErrType }); it must be one of ${allowedValues}`);
    }
    if (paymentErrType === undefined) {
      this._paymentErrType = null;
    } else {
      this._paymentErrType = paymentErrType;
    }
  }

  get paymentErrMessage () {
    // Gets the paymentErrMessage of this Data.
    //
    // error message of failed payment
    //
    // returns: paymentErrMessage
    // returnType: String

    return this._paymentErrMessage;
  }

  set paymentErrMessage (paymentErrMessage) {
    // Sets the paymentErrMessage of this Data.
    //
    // error message of failed payment
    //
    // returns: undefined
    // returnType: undefined

    if (paymentErrMessage === undefined) {
      this._paymentErrMessage = null;
    } else {
      this._paymentErrMessage = paymentErrMessage;
    }
  }
}

module.exports = Data;
